### ISSUE TITLE
[grafana] some dashboards seems to work not properly

### ISSUE THREAD

**Issue by phac008** [suxess-it/sx-cnp-oss#192]
some data is missing, some dashboards only have monitoring namespace selectable

**Comment by jkleinlercher** [comment]
etcd in k3d: i think it is due to the architecture of k3s/k3d why api-server and etcd are not accessible and maybe also don't expose those metrics by default. However, I found a good issue which might have the solution for this

https://github.com/k3s-io/k3s/issues/425#issuecomment-878382475 (and the comments below)

will try that. Maybe it also fixes the apiserver dashboard

**Comment by jkleinlercher** [comment]
https://github.com/kubernetes-sigs/kind/issues/2695#issuecomment-1080557639 could help for kind-Cluster in github action

**Comment by jkleinlercher** [comment]
before fixing this on k3d (which is maybe also a not representative K8s architecture), I tested also on metalstack.cloud, if this problem persists: Also on metalstack.cloud the etcd dashboard prints "No data" ... investigating on metalstack

**Comment by jkleinlercher** [comment]
Are those dashboards still in grafana and still don‘t work? If not, close this ticket

**Comment by jkleinlercher** [comment]
those dashboards got replaced by new ones
